name: issuu-downloader-bot
services:
  issuu-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/srajasimman/srajasimman/issuu-downloader-bot
    container_name: issuu-downloader-bot
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
